### ISSUE TITLE
When storage/app/wiki is a git repo, app should not show .git folders

### ISSUE THREAD

**Issue by tomcodes** [MrJuliuss/lecter-app#2]
In my context, storage/app/wiki is a symbolic link to a git repo I have in my home directory: ~/wiki
Using a symbolic link in that context works but lecter-app shows .git directory in its content instead of hiding it.

**Comment by tomcodes** [comment]
In my context, storage/app/wiki is a symbolic link to a git repo I have in my home directory: ~/wiki
Using a symbolic link in that context works but lecter-app show .git directory in its content.

**Comment by MrJuliuss** [comment]
Moved https://github.com/MrJuliuss/lecter/issues/1
